learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#set NAME Space

app_name = 'basic_app'

urlpatterns  = [

        path('other/',views.other, name ='other'),
        path('relative/',views.relative, name = 'relative')


]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render
import time

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number':100, 'time':time.ctime()}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8"> <!-- name="viewport" content="width=device-width, initial-scale=1.0" -->
    <title>Subbiah Andhra Mess</title

      <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
     integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!--"background-color: powderblue";-->
  </head>
  <body style = "background-image:url(https://thumbs.gfycat.com/FairImmaterialCatbird-size_restricted.gif); background-repeat: no-repeat; background-size: cover; height: 100%">
    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
      <div class= "navbar-nav">
        <a class = "navbar-brand" href="{% url 'index' %}">HOME</a>
        <a class = "nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a>
        <a class = "nav-item nav-link" href="{% url 'basic_app:other'%}">MESS</a>

      </div>
    </nav>


    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>


  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
{% block body_block %}
    <h1 style = "color:brown"><marquee>WELCOME Greetings</marquee></h1>
    <br>
    <br>
    <h2>This is your Food Spot, Refresh your Tummies!!</h2>
    <h2><em>Welcome to Subbiah mess</em><h2>
    <!--<h1>{{ text|cut:'world' }}</h1> -->
    <h3 style = "color :blue">Page used at: {{ time }}</h3>
    <h3>Click on Mess tab to view details</h3>
    <br>
    <br>
    <h4 style="text-align: right">Have a Good Day !!</h4>
  <!--  <h1>{{ number|add:'99' }}</h1> -->
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>

{% extends 'basic_app/base.html' %}
  {% block body_block %}

    <h1 style = "text-align: center ">WELCOME TO SUBBIAH MESS!</h1>
    <h2 style = "color:pink"><marquee>All Andhra Recipes available here</marquee></h2>
    <h3>Food Timings : </h3>
    <!--<p><img src="https://i.pinimg.com/originals/00/c9/c8/00c9c8227b052b856d9a0f9a1e1ca901.jpg" alt="Andhra Mess" style="float:right;width:542px;height:252px"</p><-->
    <ul>
      <li>Breakfast : starts from 9:00 AM</li>
      <li>Lunch : starts from 12:00 PM</li>
      <li>Dinner : starts from 8:00 PM</li>
    </ul>
    <br>
    <h3>Hostel Rooms available :</h3>
    <p></p>
    <ul>
      <li>AC Room : 6000 Rs</li>
      <li>Normal Room : 5000 Rs</li>
      <li>with Wifi, Washing machine</li>
    </ul>
    <br>
    <p style="text-align: center"><em>For Food orders please contact us at - 7299350158 --Available on Weekdays and weekends</em></p>
    <p style="text-align: center" ><a href="https://www.google.com/search?rlz=1C1CHBF_enIN824IN824&tbm=lcl&sxsrf=ACYBGNQR0rQQnBINrit_UnWNBm4VCPLG3A:1567840852589&q=subbaiah+andhra+mess&spell=1&sa=X&ved=0ahUKEwicw9Solr7kAhWWiHAKHWn2C84QBQgtKAA&biw=1366&bih=657&dpr=1">Please click <mark>here</mark> for location</a></p>
    <h4 style="text-align: center"> Take away available </h3>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>
    <a href="{% url 'basic_app:other' %}">Return to OTHER PAGE</a><br>
    <a href="{% url 'admin:index' %}">Return to ADMIN PAGE</a><br>
    <a href="{% url 'index' %}">Link TO INDEX PAGE</a>
  </body>
</html>